### ISSUE TITLE
搜索不到GAT的标准吗

### ISSUE THREAD

**Issue by xiongjianchang** [RyanHaoo/SimpleStdCN#1]

**Comment by CaptainMorch** [comment]
由于设计出发点和优先点（自用）是建筑行业标准，所以为了解决搜索结果动辄上百的问题，暂时从搜索结果中筛除了非建筑相关行业的标准，包括GA（公安）行业。但直接在搜索框中输入完整的标准号（包括年份）仍可正常下载。

因为软件的设置界面尚未开发，目前没有方法控制具体的筛选行业列表。如果你有需要，我可以更新一个使用配置文件控制的解决方案

**Comment by RyanHaoo** [comment]
由于设计出发点和优先点（自用）是建筑行业标准，所以为了解决搜索结果动辄上百的问题，暂时从搜索结果中筛除了非建筑相关行业的标准，包括GA（公安）行业。但直接在搜索框中输入完整的标准号（包括年份）仍可正常下载。

因为软件的设置界面尚未开发，目前没有方法控制具体的筛选行业列表。如果你有需要，我可以更新一个使用配置文件控制的解决方案
